---
title: "NDE1_methylation_CBT_profile"
author: "Sylvain Moser"
date: "3/8/2021"
output: 
  html_document:
    code_folding: hide
params:
  methylation_df: !r NULL
  pheno: !r NULL
  methylation_residuals: !r NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning=FALSE,message=FALSE}
library(dplyr)
library(ggplot2)
```

```{r}
prefix_statgen=ifelse(file.exists("/psycl/g/mpsstatgen/symo/dummy_file.txt"),"/psycl/g/mpsstatgen/symo/anxiety_methylation/","/Users/sylvain_moser/psycl_statgen/symo/anxiety_methylation/")
```


```{r}
meth_residuals=readRDS(params$methylation_residuals)
exposure_ID=meth_residuals %>% filter(Timepoint %in% c("b1","pe1","p24_1")) %>% pull(NID)
therapy_ID=meth_residuals %>% filter(Timepoint %in% c("T0","T4","E","K1")) %>% pull(NID)
```

# cg03308839 from the therapy analysis


# Profiles using residuals of the  methylation data 

## whole CBT profile: 

```{r}
time_df=meth_residuals %>% select(NID,Timepoint,cg03308839) %>% filter (NID %in% intersect(exposure_ID,therapy_ID)) %>% 
  mutate(Time=case_when(
    Timepoint=="T0" ~ 0,
    Timepoint=="T4" ~ 1,
    Timepoint=="b1" ~ 2,
    Timepoint=="pe1" ~ 3,
    Timepoint=="p24_1" ~ 4,
    Timepoint=="E" ~ 5,
    Timepoint=="K1" ~ 6,
))


plot_NDE1_CBT=ggplot(time_df,aes(x=Time,y=cg03308839,group=NID,colour=NID))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3,4,5,6),labels=c("T0","T4","BE","PE1h","PE24h","E","K"))+
  labs(title = "cg03308839",y="residuals methyl.")+
  theme(legend.position = "none",plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=1))
plot_NDE1_CBT
```

## Only therapy timepoints: 
```{r}
time_df=meth_residuals %>% select(NID,Timepoint,cg03308839) %>% filter (NID %in% intersect(exposure_ID,therapy_ID)) %>% 
  mutate(Time=case_when(
    Timepoint=="T0" ~ 0,
    Timepoint=="T4" ~ 1,
    Timepoint=="E" ~ 2,
    Timepoint=="K1" ~ 3
  ))

plot_NDE1_postint=ggplot(time_df,aes(x=Time,y=cg03308839,group=NID,colour=NID))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3),labels=c("T0","T4","E","K"))+
  labs(title = "cg03308839",y="residuals methyl.")+
  theme(legend.position = "none",plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),,axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=1))
plot_NDE1_postint
```

### color coded for the remission status: 
```{r}
pheno=read.csv(params$pheno,sep=";")
pheno_df=pheno %>%
  mutate(response=case_when(HAMAend/HAMA <=0.5 ~ 1,HAMAend/HAMA > 0.5 ~ 0)) %>% 
  mutate(remission=case_when(HAMAend <=7 ~1,HAMAend >7 ~0)) %>% 
  select(c(NID,response,remission))

remission_df=left_join(time_df,pheno_df)

plot_NDE1_postint_remission=ggplot(remission_df,aes(x=Time,y=cg03308839,group=NID,colour=as.factor(remission)))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3),labels=c("T0","T4","E","K"))+
  labs(title = "NDE1",y="residuals methyl.",colour="remission")+
  theme(plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),legend.title=element_text(size = 20),legend.text = element_text(size = 20),axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=as.factor(remission)))
plot_NDE1_postint_remission
```

### color coded for the response status: 

```{r}
plot_NDE1_postint_response=ggplot(remission_df,aes(x=Time,y=cg03308839,group=NID,colour=as.factor(response)))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3,4),labels=c("BE","PE1h","PE24h","E","K"))+
  labs(title = "NDE1",y="residuals methyl.",colour="response")+
  theme(plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),legend.title=element_text(size = 20),legend.text = element_text(size = 20),axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=as.factor(response)))
plot_NDE1_postint_response

```



### color coded for the remission status: 
```{r}
remission_df=left_join(time_df,pheno_df)

plot_NDE1_CBT_residuals_remission=ggplot(remission_df,aes(x=Time,y=cg03308839,group=NID,colour=as.factor(remission)))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3,4,5,6),labels=c("T0","T4","BE","PE1h","PE24h","E","K"))+
  labs(title = "NDE1",y="residuals methyl.",colour="remission")+
  theme(plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),legend.title=element_text(size = 20),legend.text = element_text(size = 20),axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=as.factor(remission)))
plot_NDE1_CBT_residuals_remission
```

### color coded for the response status: 

```{r}
plot_NDE1_CBT_residuals_response=ggplot(remission_df,aes(x=Time,y=cg03308839,group=NID,colour=as.factor(response)))+geom_line()+
  scale_x_continuous(name="Timepoints",breaks=c(0,1,2,3,4,5,6),labels=c("T0","T4","BE","PE1h","PE24h","E","K"))+
  labs(title = "NDE1",y="residuals methyl.",colour="response")+
  theme(plot.title = element_text(hjust = 0.5),panel.background = element_blank(),text = element_text(size = 30),axis.ticks=element_blank(),legend.title=element_text(size = 20),legend.text = element_text(size = 20),axis.line = element_line(colour ="darkgrey"))+
  stat_summary(fun=mean,geom="line",lwd=2,aes(group=as.factor(response)))
  plot_NDE1_CBT_residuals_response
```

